const cars = [
  {
    id: 1,
    name: "Kangoo",
    brand: "Renault",
    year: 2020,
    image: "https://example.com/images/kangoo.jpg",
    assignedTo: "Jean Dupont",
  },
  {
    id: 2,
    name: "Corsa",
    brand: "Opel",
    year: 2019,
    image: "https://example.com/images/corsa.jpg",
    assignedTo: "Julie Martin",
  },
  {
    id: 3,
    name: "Model 3",
    brand: "Tesla",
    year: 2021,
    image: "https://example.com/images/model3.jpg",
    assignedTo: "Ali Ben",
  },
  {
    id: 4,
    name: "208",
    brand: "Peugeot",
    year: 2022,
    image: "https://example.com/images/208.jpg",
    assignedTo: "Sarah Lemoine",
  },
  {
    id: 5,
    name: "Clio",
    brand: "Renault",
    year: 2018,
    image: "https://example.com/images/clio.jpg",
    assignedTo: "Michel Duran",
  },
  {
    id: 6,
    name: "i3",
    brand: "BMW",
    year: 2020,
    image: "https://example.com/images/i3.jpg",
    assignedTo: "Nina Giraud",
  },
  {
    id: 7,
    name: "Golf",
    brand: "Volkswagen",
    year: 2019,
    image: "https://example.com/images/golf.jpg",
    assignedTo: "Loïc Moreau",
  },
  {
    id: 8,
    name: "Civic",
    brand: "Honda",
    year: 2017,
    image: "https://example.com/images/civic.jpg",
    assignedTo: "Chloé Fabre",
  },
  {
    id: 9,
    name: "Leaf",
    brand: "Nissan",
    year: 2021,
    image: "https://example.com/images/leaf.jpg",
    assignedTo: "Thomas Leclerc",
  },
  {
    id: 10,
    name: "A3",
    brand: "Audi",
    year: 2020,
    image: "https://example.com/images/a3.jpg",
    assignedTo: "Emma Barret",
  },
  {
    id: 11,
    name: "Fiesta",
    brand: "Ford",
    year: 2018,
    image: "https://example.com/images/fiesta.jpg",
    assignedTo: "Yassine Hamdi",
  },
  {
    id: 12,
    name: "Zoe",
    brand: "Renault",
    year: 2022,
    image: "https://example.com/images/zoe.jpg",
    assignedTo: "Alice Renard",
  },
];

module.exports = cars;
