const cars = [
  {
    id: 1,
    name: "Kangoo",
    brand: "Renault",
    year: 2020,
    image: "https://example.com/images/kangoo.jpg",
    assignedTo: ["Jean Dupont"],
    assignementDate: new Date(),
  },
  {
    id: 2,
    name: "Corsa",
    brand: "Opel",
    year: 2019,
    image: "https://example.com/images/corsa.jpg",
    assignedTo: ["Julie Martin"],
    assignementDate: new Date(),
  },
  {
    id: 3,
    name: "Model 3",
    brand: "Tesla",
    year: 2021,
    image: "https://example.com/images/model3.jpg",
    assignedTo: ["Ali Ben"],
    assignementDate: new Date(),
  },
  {
    id: 4,
    name: "208",
    brand: "Peugeot",
    year: 2022,
    image: "https://example.com/images/208.jpg",
    assignedTo: ["Sarah Lemoine"],
    assignementDate: new Date(),
  },
  {
    id: 5,
    name: "Clio",
    brand: "Renault",
    year: 2018,
    image: "https://example.com/images/clio.jpg",
    assignedTo: ["Michel Duran"],
    assignementDate: new Date(),
  },
  {
    id: 6,
    name: "i3",
    brand: "BMW",
    year: 2020,
    image: "https://example.com/images/i3.jpg",
    assignedTo: ["Nina Giraud"],
    assignementDate: new Date(),
  },
  {
    id: 7,
    name: "Golf",
    brand: "Volkswagen",
    year: 2019,
    image: "https://example.com/images/golf.jpg",
    assignedTo: ["Loïc Moreau"],
    assignementDate: new Date(),
  },
  {
    id: 8,
    name: "Civic",
    brand: "Honda",
    year: 2017,
    image: "https://example.com/images/civic.jpg",
    assignedTo: ["Chloé Fabre"],
    assignementDate: new Date(),
  },
  {
    id: 9,
    name: "Leaf",
    brand: "Nissan",
    year: 2021,
    image: "https://example.com/images/leaf.jpg",
    assignedTo: ["Thomas Leclerc"],
    assignementDate: new Date(),
  },
  {
    id: 10,
    name: "A3",
    brand: "Audi",
    year: 2020,
    image: "https://example.com/images/a3.jpg",
    assignedTo: ["Emma Barret"],
    assignementDate: new Date(),
  },
  {
    id: 11,
    name: "Fiesta",
    brand: "Ford",
    year: 2018,
    image: "https://example.com/images/fiesta.jpg",
    assignedTo: ["Yassine Hamdi"],
    assignementDate: new Date(),
  },
  {
    id: 12,
    name: "Zoe",
    brand: "Renault",
    year: 2022,
    image: "https://example.com/images/zoe.jpg",
    assignedTo: ["Alice Renard"],
    assignementDate: new Date(),
  },
];

module.exports = cars;
